---
# Добавление пользователя и задания на Bareos server
- name: Bareos server. Добавление задания для бэкапа
  delegate_to: "backups"
  delegate_facts: true
  template: 
    src: 'templates/setup_client_job_on_server/job_{{ item }}.conf.j2'
    dest: '{{ bareos_dir }}/job/{{ ansible_hostname }}_{{ item }}.conf'
    mode: 0777 
    owner: bareos
    group: bareos
  with_items:
      - "{{ bareos_backup_type }}" 
  notify: reload_bareos_dir_server
