---
- name: Установка репозитория bareos RHEL 7
  copy:
    src: files/cenots-7-bareos.repo
    dest: /etc/yum.repos.d/bareos.repo
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  when: bareos_yum_repo_enabled | bool and ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Установка репозитория bareos RHEL 8
  copy:
    src: files/cenots-8-bareos.repo
    dest: /etc/yum.repos.d/bareos.repo
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  when: bareos_yum_repo_enabled | bool and ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Установка bareos
  package:
    name: "{{ bareos_package_name }}"
    state: present

- name: Открыть порт 9102 на клиенте
  ansible.posix.firewalld:
    port: 9102/tcp
    permanent: yes
    state: enabled
  when: services_state.ansible_facts.services['firewalld.service'] is defined and services_state.ansible_facts.services['firewalld.service'].status == "enabled"
