---
# handlers file for /home/nfofilov/Ansible/roles/bareos_client
- name: reload_bareos_dir_server
  delegate_to: "backups"
  delegate_facts: true
  # Стандартный демон не поддерживает reload. Перезагрузка производится через bconsole
  shell: sudo docker restart bareos-dir

- name: restart_bareos_fd_server
  service: name=bareos-fd state=restarted
  delegate_to: "backups"
  delegate_facts: true

- name: restart_bareos_fd_client
  service: name=bareos-fd state=restarted

- name: reload_bareos_fd_server
  service: name=bareos-fd state=restarted
  delegate_to: "backups"
  delegate_facts: true

- name: firewalld reload
  command: firewall-cmd --reload
  delegate_to: "backups"
  delegate_facts: true

- name: restart_bareos_fd_client
  service: name=bareos-fd state=restarted

- name: reload_firewalld_client
  command: firewall-cmd --reload
  when: services_state.ansible_facts.services['firewalld.service'] is defined and services_state.ansible_facts.services['firewalld.service'].status == "enabled"
